### ISSUE TITLE
Add templating 

### ISSUE THREAD

**Issue by logan-connolly** [logan-connolly/AoC#3]
# Todos

- [ ] Spec out python and golang solution templates 
- [ ] Implement CLI for generating solution skeletons
- [ ] Update Makefile accordingly

In the end, I should be able to call something like this:

```shell
make skeleton lang=python year=2022 day=1
make skeleton lang=golang year=2022 day=1
```

And the following should be generated:
- All languages: solution directory (ie. `./2022/01/`), `input.txt`
- Python: `main.py`
- Golang: `main.go` and `main_test.go`

**Comment by logan-connolly** [comment]
# Todos

- [ ] Spec out python and golang solution templates 
- [ ] Implement CLI for generating solution skeletons
- [ ] Update Makefile accordingly

In the end, I should be able to call something like this:

```shell
make skeleton lang=python year=2022 day=1
make skeleton lang=golang year=2022 day=1
```
